### ISSUE TITLE
Probably reduntant code

### ISSUE THREAD

**Issue by jonano614** [cheatoshin/cheatcoin#1]
https://github.com/cheatoshin/cheatcoin/blob/75896e4dba64e91a95af29771419ad9a57309bfe/cheatcoin/pool.c#L636

cheatcoin_generate_random_array(task->nonce.data, sizeof(cheatcoin_hash_t));
memcpy(task->nonce.data, hash, sizeof(cheatcoin_hashlow_t));

It looks like first line generates random array in buffer task->nonce.data and second line overwrites generated data then.

**Comment by cheatoshin** [comment]
The second line overwrites only 24 first bytes, but the first line generates random array of 32 bytes.

**Comment by jonano614** [comment]
Nice :)
I'd suggest something like 
cheatcoin_generate_random_array(task->nonce.data+sizeof(cheatcoin_hashlow_t), sizeof(cheatcoin_hash_t) - sizeof(cheatcoin_hashlow_t));
but it is not so urgent.
