### ISSUE TITLE
Unable to get this compiling on Windows (VC 2017 Community 15.5.3)

### ISSUE THREAD

**Issue by HansOlavS** [cheatoshin/cheatcoin#3]
Hi Daniel. I'm getting these errors when trying to compile win64 xdag:
* cheatcoin-master\dnet\system.h(5): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory
* \openssl-master\include\openssl\e_os2.h(13): fatal error C1083: Cannot open include file: 'openssl/opensslconf.h': No such file or directory

I suspect the probem lies with openssl as I just fetched the source from openssl master-branch on github. How should I install it?

Would love it if you could give me a pointer or two as I have faith in this project!

**Comment by jonano614** [comment]
Hi HansOlavS, you can either download pthread and openssl libraries separately or use download them using nuget. See my fork: https://github.com/jonano614/cheatcoin/tree/Project_configuration. 
The project xdag is compilable in Debug x64 mode. GuiWallet project is not compilable now, so you need to unload that project.

**Comment by HansOlavS** [comment]
Thanks @jonano614, I got it compiling now... I'm just fiddling with optimizing the SHA256 code for better mining...

**Comment by jonano614** [comment]
@HansOlavS, take into account - transferring does not work in my version. I changed mutex type in one place (you can find it in commit). Without that change I face a deadlock while application initialization.
